# Generated by Django 5.0.6 on 2024-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='Release_date',
            field=models.DateTimeField(),
        ),
    ]
